(() => {
const app=document.getElementById('app'),toastEl=document.getElementById('toast'),p=new URLSearchParams(location.search);
const state={
  started:p.get('started')==='1'||p.get('work')==='1',workStarted:p.get('work')==='1',completed:p.get('completed')==='1'||p.get('paid')==='1',
  before:+(p.get('before')||0),work:+(p.get('workshots')||0),finish:+(p.get('finishshots')||0),conditions:+(p.get('conditions')||0),
  reviewed:p.get('conditionsReviewed')==='1'||+(p.get('conditions')||0)>0,approval:p.get('approval')||'none',paid:p.get('paid')==='1',
  addOn:{name:'Pet-hair removal',price:40,message:'There’s heavy pet hair embedded in the rear cargo area. I can take care of it while I’m here for an additional $40.'},
  recordOpen:false,proofBefore:2,proofAfter:1,rebook:'6 weeks',rebookCustom:'',rebooked:false
};
if(state.completed){state.started=false;state.workStarted=false;}
let route=p.get('screen')||'today',cameraMode=p.get('mode')||(state.workStarted?'work':'before');
const totalWork=()=>state.work+state.finish,totalShots=()=>state.before+totalWork(),total=()=>220+(state.approval==='approved'?state.addOn.price:0);
function toast(m){toastEl.textContent=m;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1700);}
function nav(r){route=r;try{history.replaceState(null,'','?screen='+r)}catch{}render();scrollTo(0,0)}
window.nav=nav;window.setRoute=r=>{route=r;render()};
function topNav(t){return `<div class="navtop"><button class="icon-btn back" onclick="historyBack()" aria-label="Back">‹</button><div class="navtop-title">${t}</div><div></div></div>`}
function stage(n){return `<div class="stage">${['Details','Before','Work','Finish'].map((x,i)=>`<div class="stage-item ${i<n?'done':i===n?'current':''}"><div class="stage-bar"></div><div class="stage-label">${x}</div></div>`).join('')}</div>`}
const customerStrip=()=>`<div class="client-view-strip"><span class="client-view-badge">CUSTOMER VIEW</span><span>Private link · no app needed</span></div>`;
const bridge=(label,target)=>`<button class="demo-bridge" onclick="nav('${target}')"><span>DEMO</span>${label} →</button>`;
window.historyBack=()=>nav(({quote:'today',quoteCustomer:'quote',quoteConfirmed:'quoteCustomer',job:'today',completedJob:'today',active:'job',camera:cameraMode==='proof'?'proofcheck':'active',conditions:'active',addon:'active',customer:'addon',customerResponse:'customer',proofcheck:'active',complete:'proofcheck',pay:'complete',rebook:'pay',rebookConfirmed:'rebook'})[route]||'today');
const tabs=`<div class="tabbar"><button class="tab active" onclick="nav('today')"><span class="tab-icon"></span><span>Today</span></button><button class="tab" onclick="toast('Jobs view is outside this focused demo')"><span class="tab-icon"></span><span>Jobs</span></button><button class="tab" onclick="toast('Customer history is shown inside Sarah’s job')"><span class="tab-icon"></span><span>Customers</span></button><button class="tab" onclick="toast('Settings are outside this focused demo')"><span class="tab-icon"></span><span>More</span></button></div>`;

function today(){
  const status=state.completed?'COMPLETED':state.started?'IN PROGRESS':'NEXT',cl=state.completed?'completed':state.started?'started':'',target=state.completed?'completedJob':'job';
  const action=state.completed?`<div class="home-complete"><span>✓</span><div><strong>Job complete</strong><small>${state.paid?`Paid · $${total()}`:`Payment request sent · $${total()}`}</small></div></div>`:`<button class="primary home-start ${state.started?'resume':''}" onclick="${state.started?"nav('active')":'startJob()'}">${state.started?'Resume job':'Start job'} <span class="arrow-inline">→</span></button>`;
  return `<main class="screen"><div class="topbar"><div class="brand">COASTAL DETAIL</div><button class="top-action" onclick="nav('quote')">New request</button></div><div class="headline-row"><div><h1>Today</h1><div class="date muted">Sunday, September 6</div></div></div><div class="metrics"><div class="metric"><strong>$1,140</strong><span>Scheduled</span></div><div class="metric"><strong>4</strong><span>Jobs</span></div><div class="metric"><strong>$520</strong><span>Unpaid</span></div></div><div class="stack-note"><span class="stack-dot"></span><div><strong>Fits your existing stack</strong><span>Google Calendar synced · Square stays connected</span></div></div><div class="section-head"><div class="section-title">Schedule</div></div><div class="list"><div class="next-job-block"><div class="job-row next-job-row ${cl}" role="button" tabindex="0" onclick="nav('${target}')"><div class="job-time">9:00<span class="next ${cl}">${status}</span></div><div><div class="job-name">Sarah Chen</div><div class="job-desc">Tesla Model Y · Full detail</div></div><div class="job-price">$${state.completed?total():220}<span class="chev">›</span></div></div>${action}</div>${[['11:30','Owen Park','BMW X3 · Interior','$180'],['2:00','Maya Lopez','Subaru Outback · Wash + wax','$160'],['4:30','Chris Nguyen','Ford F-150 · Exterior detail','$240']].map(j=>`<div class="job-row passive"><div class="job-time">${j[0]}</div><div><div class="job-name">${j[1]}</div><div class="job-desc">${j[2]}</div></div><div class="job-price">${j[3]}</div></div>`).join('')}</div><div class="attention"><div class="attention-head"><span>Needs attention</span><span class="count">2</span></div><div class="attention-row"><span>Invoice #1048 · 3 days overdue</span><strong>$260</strong></div><div class="attention-row"><span>Approval waiting · Jordan Lee</span><strong>+$45</strong></div></div>${tabs}</main>`;
}
function quote(){return `<main class="screen no-tabs">${topNav('New request')}<div class="eyebrow">Booking request · 2 min ago</div><h1 class="compact-title">Sarah Chen</h1><div class="sub">2025 Tesla Model Y · White · Capitola</div><div class="request-card"><div class="request-row"><span>Requested</span><strong>Full detail</strong></div><div class="request-row"><span>Preferred time</span><strong>Sunday · 9:00 AM</strong></div><div class="request-row"><span>Customer note</span><strong>Coffee stain, rear seat</strong></div></div><div class="quote-guidance"><div class="quote-kicker">Price guidance</div><div class="guidance-main"><div><strong>$220 recommended</strong><span>Full detail template $200 · Model Y / prior jobs suggest +$20</span></div><div class="guidance-price">$220</div></div><div class="history-chip">Your last 8 similar jobs · $210–235 · ~2 hr</div></div><div class="field"><label>QUOTE</label><input class="input" value="$220"></div><div class="field"><label>MESSAGE</label><textarea class="input">Full detail for your Model Y, including the rear-seat stain you mentioned. I can be there Sunday at 9:00 AM.</textarea></div><div class="integration-line"><span>↻</span><div><strong>No migration required</strong><small>Keep Google Calendar and Square; CoastOps handles the job workflow.</small></div></div><div class="sticky-action"><div class="sticky-kicker">One tap to customer</div><button class="primary" onclick="nav('quoteCustomer')">Send $220 quote →</button></div></main>`}
function quoteCustomer(){return `<main class="customer-shell">${customerStrip()}<div class="customer-brand"><div class="name">COASTAL DETAIL</div><div class="meta">Mateo · Mobile detailing</div></div><div class="eyebrow">Quote from Mateo</div><h1>Full detail · $220</h1><div class="sub">Sunday at 9:00 AM · 2025 Tesla Model Y</div><div class="customer-service-card"><div><strong>Full detail</strong><span>Exterior, wheels, interior, windows + rear-seat stain</span></div><strong>$220</strong></div><div class="plain-note">No account needed. Approving confirms the service, price and appointment.</div><div class="customer-action"><button class="primary" onclick="nav('quoteConfirmed')">Approve $220</button></div></main>`}
function quoteConfirmed(){return `<main class="customer-shell confirmation-shell">${customerStrip()}<div class="customer-brand"><div class="name">COASTAL DETAIL</div><div class="meta">Mateo · Mobile detailing</div></div><div class="confirm-mark">✓</div><h1>You’re booked.</h1><div class="sub">Full detail · $220<br>Sunday at 9:00 AM</div><div class="confirmation-card"><strong>We’ll text you before arrival.</strong><span>No app or account needed.</span></div>${bridge('Continue on Mateo’s phone','today')}</main>`}
window.startJob=()=>{nav('active');setTimeout(()=>toast('Start with a quick before walkaround'),70)};

function completedJob(){return `<main class="screen no-tabs">${topNav('Sarah Chen')}${stage(3)}<div class="complete-mark">✓</div><h1 class="finish-title">Job complete.</h1><div class="sub finish-sub">2025 Tesla Model Y · Full detail · completed 10:42 AM</div><div class="proof-summary"><div><strong>${totalShots()}</strong><span>job photos</span></div><div><strong>${state.conditions||3}</strong><span>existing conditions</span></div><div><strong>${state.approval==='approved'?1:0}</strong><span>approved add-on</span></div></div><div class="status-banner completed-record"><strong>${state.paid?`Paid · $${total()}`:`Payment requested · $${total()}`}</strong><span>${state.paid?'Receipt sent to Sarah':'Customer payment link sent'}</span></div><div class="bill"><div class="bill-row"><span>Full detail</span><strong>$220</strong></div>${state.approval==='approved'?`<div class="bill-row"><span>${state.addOn.name}</span><strong>$${state.addOn.price}</strong></div>`:''}<div class="bill-row bill-total"><span>Total</span><strong>$${total()}</strong></div></div><button class="secondary completed-home-button" onclick="nav('today')">Back to Today</button></main>`}
function job(){if(state.completed)return completedJob();return `<main class="screen no-tabs">${topNav('Sarah Chen')}${stage(0)}<section class="summary"><h1>9:00 AM</h1><div class="vehicle">2025 Tesla Model Y · White</div><div class="summary-grid"><div class="summary-item"><label>Service</label><div>Full detail</div></div><div class="summary-item"><label>Quoted</label><div>$220</div></div><div class="summary-item"><label>Address</label><div>412 Bay Ave</div></div><div class="summary-item"><label>Duration</label><div>~2 hours</div></div></div></section>${state.started?`<div class="job-started-inline"><span class="live-dot"></span><div><strong>Job in progress</strong><span>Started 9:13 AM · Resume the active workflow</span></div></div>`:''}<div class="approval-proof"><span class="approval-check">✓</span><div><strong>Quote approved · $220</strong><span>Sarah approved yesterday at 6:14 PM · booking link</span></div></div><div class="section-head"><div class="section-title">Job details</div></div><div class="info-row"><div class="left"><div class="label">Customer note</div><div class="detail">Coffee stain on rear passenger seat</div></div><span class="chev">›</span></div><div class="info-row"><div class="left"><div class="label">Vehicle history</div><div class="detail">3 prior services · 18 previous photos</div></div><span class="chev">›</span></div><div class="section-head scope-head"><div class="section-title">Service scope</div></div><div class="scope-list"><div class="scope-row"><span class="scope-dot"></span><span>Exterior wash + wheels</span></div><div class="scope-row"><span class="scope-dot"></span><span>Interior vacuum + surfaces</span></div><div class="scope-row"><span class="scope-dot"></span><span>Windows + final wipe-down</span></div></div><div class="sticky-action"><div class="sticky-kicker">${state.started?'Active now':'Next step'}</div><button class="primary" onclick="${state.started?"nav('active')":'startJob()'}">${state.started?'Resume job':'Start job'} →</button></div></main>`}
function conditionRecord(){if(!state.before||!state.conditions)return'';return `<button class="condition-record ${state.reviewed?'confirmed':''}" onclick="nav('conditions')"><span class="condition-icon">${state.reviewed?'✓':'!'}</span><div><strong>${state.conditions} existing conditions ${state.reviewed?'confirmed':'found'}</strong><span>${state.reviewed?'Included in the pre-job record':'Quick review before work begins'}</span></div><span>›</span></button>`}
function active(){
  let next;if(!state.before)next=`<div class="sticky-action"><div class="sticky-kicker">Next step</div><button class="primary" onclick="openCamera('before')">Take before photos →</button></div>`;else if(!state.reviewed)next=`<div class="sticky-action"><div class="sticky-kicker">Before record</div><button class="primary" onclick="nav('conditions')">Review ${state.conditions||3} conditions →</button></div>`;else if(!state.workStarted)next=`<div class="sticky-action"><div class="sticky-kicker">Before record ready</div><button class="primary" onclick="beginWork()">Begin work →</button></div>`;else if(!totalWork())next=`<div class="sticky-action"><div class="sticky-kicker">Next step</div><button class="primary" onclick="openCamera('work')">Take job photos →</button></div>`;else next=`<div class="sticky-action"><div class="sticky-kicker">Next step</div><div class="sticky-split"><button class="secondary accent" onclick="openCamera('work')">More photos</button><button class="primary" onclick="nav('proofcheck')">Review & finish →</button></div></div>`;
  const issue=state.workStarted&&totalWork()&&state.approval==='none'?`<button class="issue-suggestion" onclick="nav('addon')"><div class="issue-kicker">Needs review</div><div class="issue-main"><div><strong>Pet hair · rear cargo</strong><span>Suggested add-on from your price history</span></div><div class="issue-price">+$40 ›</div></div></button>`:'';
  const approval=state.approval==='approved'?`<div class="approval-saved"><span class="approval-check">✓</span><div><strong>Customer approved · +$${state.addOn.price}</strong><span>Sarah · 10:04 AM · photo, price and response saved</span></div></div>`:state.approval==='declined'?`<div class="approval-saved declined"><span class="approval-check">—</span><div><strong>Extra work declined</strong><span>Sarah · 10:04 AM · response saved to job</span></div></div>`:'';
  return `<main class="screen no-tabs">${topNav(state.started?'Active job':'Before walkaround')}${stage(state.workStarted?2:1)}${state.started?`<div class="started-banner"><span class="live-dot"></span><div class="started-copy"><strong>Job in progress</strong><span>Started 9:13 AM · before-photo timestamps preserved</span></div><span class="started-badge">ACTIVE</span></div>`:`<div class="prestart-banner"><span class="prestart-dot"></span><div><strong>Before work begins</strong><span>Capture the walkaround first · active work starts afterward</span></div><span class="prestart-badge">PRE-JOB</span></div>`}<div class="workspace-title"><h1>Sarah Chen</h1><div class="sub">Tesla Model Y · Full detail</div></div><button class="photo-hub" onclick="openCamera('${state.workStarted?'work':'before'}')"><div class="photo-hub-head"><div class="camera-icon"></div><div><div class="photo-hub-title">${state.workStarted?'Job photos':'Before walkaround'}</div><div class="photo-hub-sub">${state.workStarted?'Keep shooting as you work. CoastOps organizes later.':'Shoot freely. Capture times preserve what happened before work starts.'}</div></div><div class="camera-count">${state.workStarted?totalWork():state.before} ›</div></div></button>${state.before?`<button class="record-line" onclick="openCamera('before')"><div><strong>Before photos</strong><span>${state.before} photos · ${state.conditions||3} conditions ${state.reviewed?'confirmed':'to review'}</span></div><div class="record-lock">Edit ›</div></button>`:''}${conditionRecord()}${issue}${approval}${next}</main>`;
}
window.beginWork=()=>{state.started=true;state.workStarted=true;nav('active');setTimeout(()=>toast('Work started · before record preserved'),70)};
window.openCamera=m=>{cameraMode=m;nav('camera')};

function carGraphic(){return `<div class="camera-car-placeholder" aria-hidden="true"><svg viewBox="0 0 760 430"><defs><linearGradient id="bp" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#f6f8f8"/><stop offset=".45" stop-color="#ccd3d2"/><stop offset=".72" stop-color="#8c9694"/><stop offset="1" stop-color="#e9eceb"/></linearGradient><linearGradient id="gl" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#718180"/><stop offset="1" stop-color="#1b2324"/></linearGradient><radialGradient id="rim"><stop offset="0" stop-color="#a4adac"/><stop offset=".42" stop-color="#434b4b"/><stop offset="1" stop-color="#15191a"/></radialGradient></defs><ellipse cx="384" cy="342" rx="292" ry="38" fill="#050708" opacity=".38"/><path d="M106 274C126 235 177 214 245 204L310 132C327 113 350 104 382 104L491 108C520 109 543 121 560 143L603 201C643 210 675 230 692 261L709 291C715 303 707 315 693 317L650 322C642 276 610 246 565 246C521 246 486 278 481 326L273 326C268 278 233 246 189 246C145 246 111 278 106 323L78 318C64 315 58 305 64 292Z" fill="url(#bp)" stroke="#fff" stroke-opacity=".48" stroke-width="2"/><path d="M276 201L329 139C342 124 359 117 383 117L480 120C499 121 516 129 528 145L568 199Z" fill="url(#gl)" stroke="#b4bfbd" stroke-opacity=".42" stroke-width="2"/><path d="M386 119L382 198M315 210L306 317M507 210L518 316" stroke="#8b9593" stroke-opacity=".46" stroke-width="2"/><path d="M144 238C201 211 277 205 370 205C485 205 584 210 650 237" fill="none" stroke="#fff" stroke-opacity=".46" stroke-width="5" stroke-linecap="round"/><path d="M637 247L684 261L702 288L648 282" fill="#dff" opacity=".82"/><path d="M645 255L687 266" stroke="#fff" stroke-width="5" stroke-linecap="round"/><g transform="translate(189 319)"><circle r="54" fill="#111516"/><circle r="38" fill="url(#rim)"/><circle r="13" fill="#b7c0bf"/><path d="M0-30V30M-26-15L26 15M-26 15L26-15" stroke="#899291" stroke-width="6" stroke-linecap="round"/></g><g transform="translate(565 319)"><circle r="54" fill="#111516"/><circle r="38" fill="url(#rim)"/><circle r="13" fill="#b7c0bf"/><path d="M0-30V30M-26-15L26 15M-26 15L26-15" stroke="#899291" stroke-width="6" stroke-linecap="round"/></g></svg><div>CAMERA PREVIEW PLACEHOLDER</div></div>`}
function camera(){
  const count=cameraMode==='before'?state.before:cameraMode==='proof'?state.finish:totalWork(),left=Math.max(0,2-state.finish),done=cameraMode==='proof'&&left===0,target=state.finish===0?['Rear seats','Capture one clear finished angle']:state.finish===1?['Passenger exterior','One clean final angle']:['Coverage complete','Both recommended shots are captured'];
  const thumbs=Array.from({length:Math.min(count,6)},(_,i)=>cameraMode==='before'?`<button class="thumb editable-thumb" onclick="removeBeforePhoto(event)" aria-label="Remove photo ${i+1}"><span>×</span></button>`:'<div class="thumb"></div>').join('');
  const hint=cameraMode==='before'?'Walk around once · add or remove photos before work begins':cameraMode==='work'?'Keep shooting — organization happens later':target[1];
  return `<main class="camera-screen ${cameraMode==='proof'?'proof-camera':''}"><div class="viewfinder">${carGraphic()}</div><div class="camera-top"><button class="icon-btn" onclick="historyBack()">×</button><div class="camera-title">${cameraMode==='before'?'Before walkaround':cameraMode==='proof'?'Finish coverage':'Sarah · Model Y'}</div><div style="width:42px"></div></div>${cameraMode==='proof'?`<div class="proof-target-card ${done?'complete':''}"><span>${done?'✓':state.finish+1}</span><div><strong>${target[0]}</strong><small>${hint}</small></div></div>`:`<div class="camera-hint">${hint}</div>`}<div class="camera-bottom"><div class="filmstrip">${thumbs}</div><div class="capture-row"><div class="shot-count">${cameraMode==='proof'?`<strong>${left}</strong> ${left===1?'shot':'shots'} left`:`<strong>${count}</strong> photos`}</div><button class="shutter ${done?'complete':''}" onclick="capture()" aria-label="Take photo" ${done?'disabled':''}></button><button class="done-camera" onclick="finishCapture()">${done?'Review':'Done'}</button></div></div></main>`;
}
window.capture=()=>{if(cameraMode==='before')state.before++;else if(cameraMode==='proof'){if(state.finish>=2)return toast('Finish coverage is already complete');state.finish++;}else state.work++;render();if(cameraMode==='proof'&&state.finish>=2)setTimeout(()=>toast('Coverage complete · tap Review'),30)};
window.removeBeforePhoto=e=>{e?.stopPropagation?.();if(state.before<=0)return;state.before--;if(!state.before){state.conditions=0;state.reviewed=false}render()};
window.finishCapture=()=>{if(cameraMode==='proof'){nav('proofcheck');if(state.finish)setTimeout(()=>toast(state.finish>=2?'Finish coverage complete':'One recommended shot remains'),80);return}const count=cameraMode==='before'?state.before:totalWork();if(!count)return toast('Take at least one photo first');if(cameraMode==='before'){state.conditions=3;state.reviewed=false;nav('conditions');setTimeout(()=>toast(`${state.before} photos saved · 3 existing conditions found`),80)}else{nav('active');setTimeout(()=>toast(`${totalWork()} job photos organized`),80)}};

function conditions(){const items=[['Rear bumper','Light scratch near passenger corner'],['Front-right wheel','Existing curb rash'],['Passenger door','Small door ding below handle']];return `<main class="screen no-tabs">${topNav('Review conditions')}<div class="eyebrow">Found in the before walkaround</div><h1 class="compact-title">Confirm what was already here.</h1><div class="sub">CoastOps found likely pre-existing conditions. You stay in control.</div><div class="condition-list">${items.map((x,i)=>`<div class="condition-item"><div class="condition-thumb variant-${i+1}"></div><div><strong>${x[0]}</strong><span>${x[1]}</span></div><span class="condition-check">✓</span></div>`).join('')}</div><button class="utility-line" onclick="toast('Add condition manually')"><span>+ Add something CoastOps missed</span><span>›</span></button><div class="plain-note">Capture times and later edits remain in the job record.</div><div class="sticky-action"><div class="sticky-kicker">One quick review</div><button class="primary" onclick="confirmConditions()">Confirm 3 conditions →</button></div></main>`}
window.confirmConditions=()=>{state.conditions=3;state.reviewed=true;nav('active');setTimeout(()=>toast('Pre-job record confirmed'),70)};
function addon(){return `<main class="screen no-tabs">${topNav('Review extra work')}<div class="eyebrow">Suggested from job photo</div><h1 class="compact-title">Pet hair detected</h1><div class="sub">Rear cargo area · photographed at 9:48 AM</div><div class="attachment hero-attachment"><div class="attachment-thumb"></div><div><strong>Rear cargo area</strong><span>Job photo · 9:48 AM</span></div><button class="link" onclick="toast('Original job photo opened')">View</button></div><div class="suggested"><div><strong>Suggested price: $40</strong><br><span>Your last 6 pet-hair add-ons: $35–50 · ~20 min</span></div><div class="price">$40</div></div><div class="field"><label>ITEM</label><input class="input" id="addonName" value="${state.addOn.name}"></div><div class="field"><label>PRICE</label><input class="input" id="addonPrice" value="$${state.addOn.price}"></div><div class="field"><label>MESSAGE TO CUSTOMER</label><textarea class="input" id="addonMsg">${state.addOn.message}</textarea></div><div class="sticky-action"><div class="sticky-kicker">Confirm suggestion</div><button class="primary" onclick="sendApproval()">Send approval request →</button></div></main>`}
window.sendApproval=()=>{state.addOn.name=document.getElementById('addonName').value;state.addOn.price=parseFloat(document.getElementById('addonPrice').value.replace(/[^0-9.]/g,''))||40;state.addOn.message=document.getElementById('addonMsg').value;state.approval='pending';nav('customer')};
function customer(){return `<main class="customer-shell">${customerStrip()}<div class="customer-brand"><div class="name">COASTAL DETAIL</div><div class="meta">Your detail is in progress</div></div><div class="eyebrow">Quick approval</div><h1>One extra item</h1><div class="sub">Mateo found something outside your approved $220 service.</div><div class="proof-photo"><div class="caption">Rear cargo area · 9:48 AM</div></div><div class="approval-card"><h2>${state.addOn.name}</h2><p class="sub" style="margin-top:7px">${state.addOn.message}</p><div class="price-line"><span class="sub">Added to today’s total</span><strong>+$${state.addOn.price}</strong></div></div><div class="customer-action"><div class="choice-row approval-choice"><button class="primary" onclick="respond('approved')">Approve +$${state.addOn.price}</button><button class="secondary" onclick="respond('declined')">No thanks</button></div></div></main>`}
window.respond=x=>{state.approval=x;nav('customerResponse')};
function customerResponse(){const ok=state.approval==='approved';return `<main class="customer-shell confirmation-shell">${customerStrip()}<div class="customer-brand"><div class="name">COASTAL DETAIL</div><div class="meta">Your detail is in progress</div></div><div class="confirm-mark">${ok?'✓':'—'}</div><h1>${ok?'Approved.':'No problem.'}</h1><div class="sub">${ok?`$${state.addOn.price} ${state.addOn.name.toLowerCase()} was added to today’s service.`:`${state.addOn.name} was declined. Your original service is unchanged.`}</div><div class="confirmation-card"><strong>Mateo has been notified.</strong><span>You can close this page.</span></div>${bridge('Continue on Mateo’s phone','active')}</main>`}
function proofcheck(){const missing=Math.max(0,2-state.finish),ready=!missing;return `<main class="screen no-tabs">${topNav('Finish check')}${stage(3)}<div class="eyebrow">CoastOps checked the job photos</div><h1 class="finish-title">${ready?'Proof coverage looks good.':`${missing} quick shot${missing===1?'':'s'} recommended.`}</h1><div class="sub finish-sub">${ready?'Enough coverage to build the customer handoff.':'You can finish now, but these shots will make the proof stronger.'}</div><div class="coverage-list"><div class="coverage-row done"><span class="coverage-mark">✓</span><div><strong>Exterior transformation</strong><span>Covered by existing job photos</span></div><span>Ready</span></div><div class="coverage-row ${state.finish>=1?'done':'missing'}"><span class="coverage-mark">${state.finish>=1?'✓':'!'}</span><div><strong>Rear seats</strong><span>${state.finish>=1?'Clear finished photo added':'No clear finished angle found'}</span></div><span>${state.finish>=1?'Ready':'Shoot'}</span></div><div class="coverage-row ${state.finish>=2?'done':'missing'}"><span class="coverage-mark">${state.finish>=2?'✓':'!'}</span><div><strong>Passenger exterior</strong><span>${state.finish>=2?'Clear finished photo added':'Final angle is weak'}</span></div><span>${state.finish>=2?'Ready':'Shoot'}</span></div></div><div class="sticky-action"><div class="sticky-kicker">${ready?'Proof ready':'About 15 seconds'}</div>${ready?`<button class="primary" onclick="nav('complete')">Review proof package →</button>`:`<div class="sticky-split"><button class="secondary" onclick="nav('complete')">Finish anyway</button><button class="primary" onclick="openCamera('proof')">Take ${missing} shot${missing===1?'':'s'} →</button></div>`}</div></main>`}
function proofChoice(kind,label,sel,count){return `<div class="proof-choice"><div class="compare-img ${kind==='after'?'after-image':''}"></div><div class="proof-choice-meta"><div><strong>${label}</strong><span>Photo ${sel} of ${Math.max(sel,count)} · selected automatically</span></div><button onclick="cycleProof('${kind}')">Change</button></div></div>`}
window.cycleProof=k=>{if(k==='before')state.proofBefore=state.proofBefore>=Math.max(2,state.before)?1:state.proofBefore+1;else state.proofAfter=state.proofAfter>=Math.max(2,totalWork())?1:state.proofAfter+1;render();setTimeout(()=>toast(`${k==='before'?'Before':'After'} proof updated`),40)};
function complete(){return `<main class="screen no-tabs">${topNav('Proof package')}${stage(3)}<div class="complete-mark">✓</div><h1 class="finish-title">Ready to send.</h1><div class="sub finish-sub">CoastOps picked the strongest proof. Change either image if you prefer another.</div><div class="proof-summary"><div><strong>${totalShots()}</strong><span>job photos</span></div><div><strong>${state.conditions||3}</strong><span>existing conditions</span></div><div><strong>${state.approval==='approved'?1:0}</strong><span>approved add-on</span></div></div><div class="proof-choice-grid">${proofChoice('before','BEFORE',state.proofBefore,state.before)}${proofChoice('after','AFTER',state.proofAfter,totalWork())}</div><div class="bill"><div class="bill-row"><span>Full detail</span><strong>$220</strong></div>${state.approval==='approved'?`<div class="bill-row"><span>${state.addOn.name}</span><strong>$${state.addOn.price}</strong></div>`:''}<div class="bill-row bill-total"><span>Total</span><strong>$${total()}</strong></div></div><div class="sticky-action"><div class="sticky-kicker">Complete job</div><button class="primary" onclick="sendProof()">Send proof + request $${total()} →</button></div></main>`}
window.sendProof=()=>{state.completed=true;state.started=false;state.workStarted=false;nav('pay')};
function serviceRecord(){return state.recordOpen?`<div class="service-record"><div><strong>${totalShots()}</strong><span>job photos</span></div><div><strong>${state.conditions||3}</strong><span>existing conditions</span></div><div><strong>${state.approval==='approved'?1:0}</strong><span>approved extra</span></div></div>`:''}
window.toggleRecord=()=>{state.recordOpen=!state.recordOpen;render()};
function pay(){return `<main class="customer-shell">${customerStrip()}<div class="customer-brand"><div class="name">COASTAL DETAIL</div><div class="meta">Completed today · 10:42 AM</div></div><div class="complete-mark">✓</div><h1>Your Model Y is ready.</h1><div class="sub">Full detail completed. Here’s your finished car and today’s total.</div><div class="compare customer-compare"><div class="compare-item"><div class="compare-img"></div><div class="compare-label">BEFORE</div></div><div class="compare-item"><div class="compare-img"></div><div class="compare-label">AFTER</div></div></div><div class="completed-service"><span>Full detail</span><strong>Completed ✓</strong></div><div class="bill"><div class="bill-row"><span>Full detail</span><strong>$220</strong></div>${state.approval==='approved'?`<div class="bill-row"><span>${state.addOn.name} · approved</span><strong>$${state.addOn.price}</strong></div>`:''}<div class="bill-row bill-total"><span>Total</span><strong>$${total()}</strong></div></div><button class="service-record-toggle" onclick="toggleRecord()"><span>${state.recordOpen?'Hide':'View'} service record</span><span>${state.recordOpen?'−':'+'}</span></button>${serviceRecord()}${state.paid?`<div class="status-banner"><strong>Paid · $${total()}</strong><span>Visa ending in 4242 · receipt sent</span></div>`:`<div class="payment-provider">Secure payment · Square</div>`}<div class="customer-action"><button class="primary" onclick="payNow()">${state.paid?'Book maintenance detail':`Pay $${total()}`}</button></div></main>`}
window.payNow=()=>{if(!state.paid){state.paid=true;render();setTimeout(()=>toast('Payment received'),60)}else nav('rebook')};
function rebook(){const opts=['4 weeks','6 weeks','8 weeks','Other'],other=state.rebook==='Other';return `<main class="customer-shell">${customerStrip()}<div class="customer-brand"><div class="name">COASTAL DETAIL</div><div class="meta">Maintenance scheduling</div></div><div class="eyebrow">Keep it this clean</div><h1>When should Mateo come back?</h1><div class="sub">Pick a rough interval. Mateo will confirm the exact date with you.</div><div class="rebook-options">${opts.map(o=>`<button class="${state.rebook===o?'selected':''}" onclick="selectRebook('${o}')"><span><strong>${o}</strong>${o==='6 weeks'?'<small>Recommended</small>':o==='Other'?'<small>Choose another timeframe</small>':''}</span><span>${state.rebook===o?'✓':'›'}</span></button>`).join('')}</div>${other?`<div class="rebook-other"><label>WHEN WORKS BETTER?</label><input class="input" id="rebookOther" value="${state.rebookCustom}" placeholder="e.g. 3 months, before Thanksgiving"></div>`:''}<div class="plain-note">No subscription. This sends a maintenance request using the same vehicle and service history.</div><div class="customer-action"><button class="primary" onclick="confirmRebook()">${other?'Send timing request':`Request ${state.rebook}`} →</button></div></main>`}
window.selectRebook=o=>{state.rebook=o;render()};
window.confirmRebook=()=>{if(state.rebook==='Other'){const x=document.getElementById('rebookOther')?.value.trim()||'';if(!x)return toast('Add a preferred timeframe');state.rebookCustom=x}state.rebooked=true;nav('rebookConfirmed')};
function rebookConfirmed(){const timing=state.rebook==='Other'?`Mateo will follow up about “${state.rebookCustom}” to confirm a maintenance detail.`:`Mateo will reach out around ${state.rebook} from now to confirm a maintenance detail.`;return `<main class="customer-shell confirmation-shell">${customerStrip()}<div class="customer-brand"><div class="name">COASTAL DETAIL</div><div class="meta">Maintenance scheduling</div></div><div class="confirm-mark">✓</div><h1>Request sent.</h1><div class="sub">${timing}</div><div class="confirmation-card"><strong>Your Model Y history is already attached.</strong><span>No forms to fill out again.</span></div><button class="demo-bridge" onclick="returnOperatorHome()"><span>DEMO</span>Return to operator home →</button></main>`}
window.returnOperatorHome=()=>{state.completed=true;state.started=false;state.workStarted=false;nav('today')};

const screens={today,quote,quoteCustomer,quoteConfirmed,job,completedJob,active,camera,conditions,addon,customer,customerResponse,proofcheck,complete,pay,rebook,rebookConfirmed};
function render(){const cv=['quoteCustomer','quoteConfirmed','customer','customerResponse','pay','rebook','rebookConfirmed'].includes(route);app.classList.toggle('customer-view-frame',cv);document.body.classList.toggle('customer-view-mode',cv);app.innerHTML=(screens[route]||today)()}
render();
})();